type ResetSetters = {
  setSellerType: (value: "private_party") => void;
  setListingSource: (value: "online_marketplace") => void;
  setBookingType: (value: "concierge") => void;
  setPlatformSource: (value: string) => void;
  setVehicleSeenLocation: (value: string) => void;
  setVehicleYear: (value: string) => void;
  setVehicleMake: (value: string) => void;
  setVehicleModel: (value: string) => void;
  setVehicleTrim: (value: string) => void;
  setVehicleVin: (value: string) => void;
  setVehicleDescription: (value: string) => void;
  setVehicleMileage: (value: string) => void;
  setVehiclePrice: (value: string) => void;
  setListingUrl: (value: string) => void;
  setVehicleLocation: (value: string) => void;
  setSellerName: (value: string) => void;
  setSellerPhone: (value: string) => void;
  setPreferredDate: (value: string) => void;
  setInspectionAddress: (value: string) => void;
  setInspectionTimeWindow: (value: string) => void;
  setNotesToInspector: (value: string) => void;
  setServiceZip: (value: string) => void;
  setZipStatus: (value: "idle") => void;
  setClassification: (value: null) => void;
  setIntakeUrl: (value: string) => void;
  setIntakeImageIds: (value: string[]) => void;
  setIntakeImageNames: (value: string[]) => void;
  setIntakeProposal: (value: null) => void;
  setIntakeOriginalProposal: (value: null) => void;
  setIntakeProvenance: (value: Record<string, unknown>) => void;
  setIntakeWarning: (value: string) => void;
  setShowWhyModal: (value: boolean) => void;
  setStep: (value: number) => void;
};

export function clearVehicleAttempt(set: ResetSetters) {
  set.setSellerType("private_party");
  set.setListingSource("online_marketplace");
  set.setBookingType("concierge");
  set.setPlatformSource("");
  set.setVehicleSeenLocation("");
  set.setVehicleYear("");
  set.setVehicleMake("");
  set.setVehicleModel("");
  set.setVehicleTrim("");
  set.setVehicleVin("");
  set.setVehicleDescription("");
  set.setVehicleMileage("");
  set.setVehiclePrice("");
  set.setListingUrl("");
  set.setVehicleLocation("");
  set.setSellerName("");
  set.setSellerPhone("");
  set.setPreferredDate("");
  set.setInspectionAddress("");
  set.setInspectionTimeWindow("");
  set.setNotesToInspector("");
  set.setServiceZip("");
  set.setZipStatus("idle");
  set.setClassification(null);
  set.setIntakeUrl("");
  set.setIntakeImageIds([]);
  set.setIntakeImageNames([]);
  set.setIntakeProposal(null);
  set.setIntakeOriginalProposal(null);
  set.setIntakeProvenance({});
  set.setIntakeWarning("");
  set.setShowWhyModal(false);
  set.setStep(0);
}